### ISSUE TITLE
Remake Figs 7 & 8 

### ISSUE THREAD

**Issue by rjsmethurst** [karenlmasters/gz-hubbleseq#1]
Sandor to provide the data - Becky to remake the plot

**Comment by rjsmethurst** [comment]
Hi @karenlmasters -  @sandor provided me with some data today and I remade the bulge strength vs arm winding plot. Not sure if that was originally figure 7 or 8 - it looks like changes have been made previously that have changed the figure numbering. 

I did all the changes on a new branch and submitted a pull request #7 

Let me know if there's another plot I'm also supposed to be remaking...

**Comment by karenlmasters** [comment]
Figure 8 was the same as 7 but with the sample divided into "Left panel: galaxies with pbar < 0.2; right panel: galaxies with pbar > 0.5". I would be interested to double check that's still the same as it was before.

**Comment by rjsmethurst** [comment]
Have made that figure for you and submitted a new pull request (#9) . Not sure what the old one showed but this shows the barred galaxies moving within this bulge strength vs arm winding space:

![image](https://user-images.githubusercontent.com/5754386/30692379-36a8c4b6-9ec3-11e7-9ae4-b3cc8f878841.png)
